name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: Unonche/unonche.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: build-repo

      - name: Copy built files to target repo
        working-directory: build
        run: |
          find ../build-repo -mindepth 1 -not -name '.git' -exec rm -rf {} +
          find . -type f -not -path '*/.git/*' -exec cp --parents {} ../build-repo \;

      - name: Commit and push changes
        working-directory: build-repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploying built project [skip ci]" || echo "Nothing to commit"
          git push origin main

